[package]
name = "waveless_frontend"
description.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[[bin]]
name = "waveless"

[dependencies]
waveless_commons.workspace = true
waveless_compiler.workspace = true
waveless_executor.workspace = true

waveless_sql = { workspace = true}

rustyrosetta = { workspace = true, features = ["all"] }

compact_str.workspace = true
mimalloc.workspace = true
clap.workspace = true
tracing.workspace = true
nestify.workspace = true
eyre.workspace = true

[features]
all = ["mysql", "postgres"]

mysql = ["waveless_sql/mysql"]
postgres = ["waveless_sql/postgres"]
