[workspace]
members = ["commons", "compiler", "runtime", "frontend"]
default-members = ["compiler"]
resolver = "3"

[workspace.package]
description = "Bring your data model → generate fast, portable and battle-ready APIs 🚀."
version = "0.4.1"
homepage = "https://github.com/nv0skar/waveless"
repository = "https://github.com/nv0skar/waveless"
edition = "2024"

[workspace.dependencies]
waveless = { path = "./frontend" }

waveless_commons = { path = "./commons" }
waveless_compiler = { path = "./compiler" }
waveless_runtime = { path = "./runtime" }

waveless_sql = { git = "https://github.com/nv0skar/waveless_sql.git" }

rustyrosetta = { git = "https://github.com/nv0skar/RustyRosetta.git", tag = "rustyrosetta_0.0.4", features = [
    "all",
] }

boxed_any = { git = "https://github.com/nv0skar/BoxedAny.git" }
boxed_any_derive = { git = "https://github.com/nv0skar/BoxedAny.git" }

tokio = "1.53"

tokio-util = "0.7"

tokio-rustls = { version = "0.26", default-features = false }
rustls = { version = "0.23", default-features = false }

futures = "0.3"

serde = { version = "1.0.229", features = ["derive", "rc"] }
toml = "1.1.6"
serde_json = "1.0"
serde_with = { version = "3.23", features = ["chrono"] }

hyper = "1"
hyper-util = "0.1"
http-body-util = "0.1"
tower = { version = "0.5.3", features = ["full"] }
tower-http = "0.7"
tower-http-cache = "0.6"
tower_governor = { git = "https://github.com/nv0skar/tower-governor-generic-result.git", default-features = false }
http = "1.5"
matchit = "0.9"

hyper-tungstenite = "0.30"

bytes = "1.12"

hex = "0.4"

sqlx = { version = "0.9.0", features = [
    "runtime-tokio",
    "tls-rustls",
    "json",
    "mysql"
] }
sea-orm = { version = "2.0.3", default-features = false }
sea-schema = { git = "https://github.com/nv0skar/sea-schema-mysql.git" }

chrono = { version = "0.4.45", default-features = false, features = [
    "clock",
    "serde",
] }

### Dependencies to implement the admin panel
# leptos = { version = "0.8.20", default-features = false }
# leptos_meta = { version = "0.8.6", default-features = false }
# leptos_router = { version = "0.8.14", default-features = false }
# leptos_dom = { version = "0.8.8", default-features = false }
# leptos_axum = { version = "0.8.10", default-features = false }

# gloo-net = { version = "0.7.0", features = ["http"] }

typetag = "0.2"
async-trait = "0.1"
dyn-clone = "1.0.20"

### Dependency to implement the query cache

# redb = "3.1.0"

### Dependency to implement the mailing

# lettre = { version = "0.11.19", features = ["tokio1", "tokio1-native-tls"] }

smallvec = { version = "1.16", features = ["serde", "write", "const_new"] }
arrayvec = { version = "0.7", features = ["serde"] }
stackalloc = "1"
smallbox = "0.8"
dashmap = { version = "6.2", features = ["serde"] }
compact_str = { version = "0.10", features = ["serde"] }

mimalloc = { version = "0.1.52", features = ["secure"] }

rand = "0.10"

# blake3 = "1.8"
# argon2 = { version = "0.6", default-features = true }
crc32fast = "1.5"

clap = { version = "4.6", features = ["derive"] }

iocraft = "0.9"
owo-colors = "4.4"

regex = "1.13"

# wasm-bindgen = "0.2.100"

tracing = "0.1"
tracing-subscriber = "0.3"
console-subscriber = "0.5"
tracing-appender = "0.2"

getset = "0.1"
nestify = "0.3"
either = { version = "1.18", features = ["serde"] }
eyre = "0.6"
color-eyre = "0.6"
thiserror = "2.0.20"
derive_builder = "0.20"
derive_more = { version = "2.1", features = ["constructor", "display"] }

[workspace.lints.rust]
unexpected_cfgs = "deny"

[workspace.dependencies.getrandom]
version = "*"
features = ["wasm_js"]

# [package.metadata.wasm-pack.profile.profiling]
# wasm-opt = false

# [[workspace.metadata.leptos]]
# name = "Waveless"
# bin-package = "waveless_compiler"
# lib-package = "waveless_frontend"
# bin-features = ["ssr", "cargo_leptos"]
# lib-features = ["hydrate"]
# site-addr = "0.0.0.0:3000"
# assets-dir = "target/bundled"
# style-file = "style/main.scss"
# tailwind-input-file = "style/tailwind.css"

[patch."https://github.com/nv0skar/waveless"]
waveless = { path = "./frontend" }

waveless_commons = { path = "./commons" }
waveless_compiler = { path = "./compiler" }
waveless_runtime = { path = "./runtime" }

[profile.dev.package."*"]
debug = false
codegen-units = 256
opt-level = 1

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
debug = false
strip = true
codegen-units = 256
lto = true
opt-level = 's'

[profile.dist]
inherits = "release"
