[package]
name = "waveless_commons"
description.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
rustyrosetta = { workspace = true, features = ["all"] }
boxed_any.workspace = true
boxed_any_derive.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "tracing"] }
hyper.workspace = true
hyper-tungstenite.workspace = true
sea-orm.workspace = true
serde = { workspace = true, features = ["rc"] }
serde_with = {workspace = true, features = ["json"]}
serde_json.workspace = true
toml.workspace = true
http.workspace = true
http-body-util.workspace = true
bytes.workspace = true
compact_str.workspace = true
dashmap.workspace = true
typetag.workspace = true
async-trait.workspace = true
dyn-clone.workspace = true
getset.workspace = true
iocraft.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
console-subscriber = { workspace = true, optional = true}
derive_builder.workspace = true
derive_more.workspace = true
eyre.workspace = true
color-eyre.workspace = true
thiserror.workspace = true

# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# tokio = { workspace = true, features = ["rt-multi-thread", "sync", "tracing"] }


# [target.'cfg(target_arch = "wasm32")'.dependencies]
# tokio = { workspace = true, features = ["sync"] }


[features]
debug = ["dep:console-subscriber"]
