[package]
name = "waveless_compiler"
version.workspace = true
edition.workspace = true

[dependencies]
waveless_commons.workspace = true
waveless_executor.workspace = true
waveless_sql = { workspace = true, features = ["mysql"]}

rustyrosetta = { workspace = true, features = ["all"] }

tokio = { workspace = true, features = ["full"] }
sea-schema.workspace = true
toml.workspace = true
compact_str.workspace = true
mimalloc.workspace = true
clap.workspace = true
crc32fast.workspace = true
owo-colors.workspace = true
tracing.workspace = true
nestify.workspace = true
chrono.workspace = true
getset.workspace = true
either.workspace = true
derive_more.workspace = true
eyre.workspace = true

[features]
all = ["mysql", "postgres"]

mysql = []
postgres = []
