[package]
name = "waveless_executor"
version.workspace = true
edition.workspace = true

[dependencies]
waveless_commons.workspace = true
waveless_sql.workspace = true

rustyrosetta = { workspace = true, features = ["all"] }

tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true, features = ["ring"] }
rustls = { workspace = true }
futures.workspace = true
hyper.workspace = true
hyper-util = { workspace = true, features = ["server-auto"] }
http-body-util.workspace = true
tower.workspace = true
tower-http = { workspace = true, features = ["full"] }
tower-http-cache.workspace = true
tower_governor.workspace = true
http.workspace = true
matchit.workspace = true
tungstenite.workspace = true
hyper-tungstenite.workspace = true
bytes.workspace = true
sqlx.workspace = true
sea-orm.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
arrayvec.workspace = true
compact_str.workspace = true
dashmap.workspace = true
rclite.workspace = true
mimalloc.workspace = true
clap.workspace = true
chrono.workspace = true
owo-colors.workspace = true
regex.workspace = true
tracing.workspace = true
nestify.workspace = true
getset.workspace = true
either.workspace = true
derive_more.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[features]
all = ["mysql", "postgres"]

mysql = []
postgres = []
